version: "3.3"
services:
  rails_mongo:
    image: "fff:fff12"
    environment:
      - PORT=3000
    volumes:
      - .:/rails_mongo
    ports:
      - "3000:3000"
    expose:
      - 3000
    links:
      - mongodb
      - rabbitmq
    depends_on:
      - mongodb
      - rabbitmq
  mongodb:
    image: "mongo:4.2.8"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=${DATABASE}
      - MONGODB_USER=${USERNAME}
      - MONGODB_PASS=${PASS}
    volumes:
      - "mongodb:/var/lib/mongodb/data"
    ports:
      - "27017:27017"
  rabbitmq:
    restart: always
    image: rabbitmq:3.8.2-management
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  mongodb:
  rabbitmq:
  rails_mongo: